### ISSUE TITLE
Unable to load configuration partial base

### ISSUE THREAD

**Issue by demozhang1029** [ecomfe/reskript#213] opened 2021-12-20 10:20 UTC
use the `npx @reskript/init` to create project.  

run `npm start` successfully but `npm run build` failed with below errors, any thoughts?
node version: v14.18.1

--------------------------------------------------------------------------------
$ npm run build

> common-charts@1.0.0 build
> skr build --clean

Unable to load configuration partial base
Command failed, you may submit a issue to https://github.com/ecomfe/reskript/issues/new

error-logs:
10 silly lifecycle common-charts@1.0.0~build: Args: [ '-c', 'skr build --clean' ]
11 silly lifecycle common-charts@1.0.0~build: Returned: code: 99  signal: null
12 info lifecycle common-charts@1.0.0~build: Failed to exec build script
13 verbose stack Error: common-charts@1.0.0 build: `skr build --clean`
13 verbose stack Exit status 99

**Comment by otakustay** [comment] 2021-12-20 10:37
Please try `SKR_LOGGING=debug skr build --clean` and paste all detailed logs

**Comment by demozhang1029** [comment] 2021-12-20 10:46
Unable to load configuration partial base
Command failed, you may submit a issue to https://github.com/ecomfe/reskript/issues/new
Error: PostCSS plugin postcss-discard-comments requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/Users/zhangxin85/Documents/code/baidu/det-drd/common-charts/node_modules/postcss/lib/processor.js:167:15)
    at new Processor (/Users/zhangxin85/Documents/code/baidu/det-drd/common-charts/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/Users/zhangxin85/Documents/code/baidu/det-drd/common-charts/node_modules/postcss/lib/postcss.js:55:10)
    at cssnanoPlugin (/Users/zhangxin85/Documents/code/baidu/det-drd/common-charts/node_modules/cssnano/dist/index.js:145:31)
    at factory (/Users/zhangxin85/Documents/code/baidu/det-drd/common-charts/node_modules/@reskript/config-webpack/dist/loaders/postCSS)
    at introduceLoader (/Users/zhangxin85/Documents/code/baidu/det-drd/common-charts/node_modules/@reskript/config-webpack/dist/utils/l)
    at /Users/zhangxin85/Documents/code/baidu/det-drd/common-charts/node_modules/@reskript/config-webpack/dist/utils/loader.js:31:100
    at Array.map (<anonymous>)
    at introduceLoaders (/Users/zhangxin85/Documents/code/baidu/det-drd/common-charts/node_modules/@reskript/config-webpack/dist/utils/)
    at /Users/zhangxin85/Documents/code/baidu/det-drd/common-charts/node_modules/@reskript/config-webpack/dist/rules/index.js:7:56
npm ERR! code ELIFECYCLE
npm ERR! errno 99
npm ERR! common-charts@1.0.0 build: `SKR_LOGGING=debug skr build --clean`

**Comment by demozhang1029** [comment] 2021-12-20 10:47
Unable to load configuration partial base
Command failed, you may submit a issue to https://github.com/ecomfe/reskript/issues/new
Error: PostCSS plugin postcss-discard-comments requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/common-charts/node_modules/postcss/lib/processor.js:167:15)
    at new Processor (/common-charts/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/common-charts/node_modules/postcss/lib/postcss.js:55:10)
    at cssnanoPlugin (/common-charts/node_modules/cssnano/dist/index.js:145:31)
    at factory (/common-charts/node_modules/@reskript/config-webpack/dist/loaders/postCSS)
    at introduceLoader (/common-charts/node_modules/@reskript/config-webpack/dist/utils/l)
    at /common-charts/node_modules/@reskript/config-webpack/dist/utils/loader.js:31:100
    at Array.map (<anonymous>)
    at introduceLoaders (/common-charts/node_modules/@reskript/config-webpack/dist/utils/)
    at /common-charts/node_modules/@reskript/config-webpack/dist/rules/index.js:7:56
npm ERR! code ELIFECYCLE
npm ERR! errno 99
npm ERR! common-charts@1.0.0 build: `SKR_LOGGING=debug skr build --clean`

**Comment by otakustay** [comment] 2021-12-20 10:48
Seems introduced by #204 , I'll have a deep look

**Comment by otakustay** [comment] 2021-12-20 10:53
I couldn't reproduce this on my local computer, would you provide a zip including `npx @reskript/init` generated content and without `node_modules`?

**Comment by demozhang1029** [comment] 2021-12-20 10:55
Sure
[common-charts.zip](https://github.com/ecomfe/reskript/files/7744737/common-charts.zip)

**Comment by demozhang1029** [comment] 2021-12-20 10:56
Do I have to follow the quick start: https://ecomfe.github.io/reskript/docs/app/quick-start first and then use the `npx @reskript/init`?

**Comment by demozhang1029** [comment] 2021-12-20 11:07
My mac version is Apple M1

**Comment by otakustay** [comment] 2021-12-20 12:42
It seems `postcss@7` is unexpectedly hoist by npm 6.x, both yarn and npm 7.x (with node 16) works well.

This is not an easy problem that can be fixed on the side of resKRipt since we want a built-in postcss but accidentally community dependency graph are different from what we are expecting

For now, I recommend to switch to newer version of npm or to use yarn ad package manager, or to run `npm i -D postcss` to force `postcss@8` to be hoisted

**Comment by demozhang1029** [comment] 2021-12-21 02:44
I tried with npm 7.x and node 16.2, failed at very beginning with errors: 
`Command failed with exit code 1: npm install -D -E @reskript/cli @reskript/cli-dev @reskript/cli-build @reskript/cli-lint @reskript/config-lint @reskript/cli-test @reskript/cli-play`

BTW, `yarn run build` works well

**Closed** 2021-12-21 02:46 UTC

**Comment by otakustay** [comment] 2021-12-21 02:49
The init exit is probably because of some network error

**Comment by demozhang1029** [comment] 2021-12-21 02:53
but npm 6.x with node 14.x init successfully

**Comment by otakustay** [comment] 2021-12-21 02:57
I'm having Node 16 with NPM 7, it succeeds always when I use our internal npm registry, but randomly fail if I reach official registry without local cache

Still, if you're failing frequently, try `SKR_LOGGING=debug npx @reskript/init .` to gain more detailed log, I'd love to fix any issues than can be fixed on our side

**Comment by demozhang1029** [comment] 2021-12-21 02:58
Thanks very much. Now yarn is enough for me.  👍
